"""empty message

Revision ID: dc07528bff05
Revises: 08707b4d1927
Create Date: 2024-06-06 20:44:42.503749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc07528bff05'
down_revision = '08707b4d1927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dorams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=50), nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dorams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
